-- Native encounter-channel presence from supplied FireRed/Emerald USA ROMs.
return {
 ["EMABANDONEDSHIPHIDDENFLOORCORRIDORS"]={ water=true, fishing=true },
 ["EMABANDONEDSHIPROOMSB1F"]={ water=true, fishing=true },
 ["EMALTERINGCAVE"]={ land=true },
 ["EMARTISANCAVE1F"]={ land=true },
 ["EMARTISANCAVEB1F"]={ land=true },
 ["EMCAVEOFORIGIN1F"]={ land=true },
 ["EMCAVEOFORIGINENTRANCE"]={ land=true },
 ["EMCAVEOFORIGINUNUSEDRUBYSAPPHIREMAP1"]={ land=true },
 ["EMCAVEOFORIGINUNUSEDRUBYSAPPHIREMAP2"]={ land=true },
 ["EMCAVEOFORIGINUNUSEDRUBYSAPPHIREMAP3"]={ land=true },
 ["EMDESERTUNDERPASS"]={ land=true },
 ["EMDEWFORDTOWN"]={ water=true, fishing=true },
 ["EMEVERGRANDECITY"]={ water=true, fishing=true },
 ["EMFIERYPATH"]={ land=true },
 ["EMGRANITECAVE1F"]={ land=true },
 ["EMGRANITECAVEB1F"]={ land=true },
 ["EMGRANITECAVEB2F"]={ land=true, rocks=true },
 ["EMGRANITECAVESTEVENSROOM"]={ land=true },
 ["EMJAGGEDPASS"]={ land=true },
 ["EMLILYCOVECITY"]={ water=true, fishing=true },
 ["EMMAGMAHIDEOUT1F"]={ land=true },
 ["EMMAGMAHIDEOUT2F1R"]={ land=true },
 ["EMMAGMAHIDEOUT2F2R"]={ land=true },
 ["EMMAGMAHIDEOUT2F3R"]={ land=true },
 ["EMMAGMAHIDEOUT3F1R"]={ land=true },
 ["EMMAGMAHIDEOUT3F2R"]={ land=true },
 ["EMMAGMAHIDEOUT3F3R"]={ land=true },
 ["EMMAGMAHIDEOUT4F"]={ land=true },
 ["EMMETEORFALLS1F1R"]={ land=true, water=true, fishing=true },
 ["EMMETEORFALLS1F2R"]={ land=true, water=true, fishing=true },
 ["EMMETEORFALLSB1F1R"]={ land=true, water=true, fishing=true },
 ["EMMETEORFALLSB1F2R"]={ land=true, water=true, fishing=true },
 ["EMMETEORFALLSSTEVENSCAVE"]={ land=true },
 ["EMMIRAGETOWER1F"]={ land=true },
 ["EMMIRAGETOWER2F"]={ land=true },
 ["EMMIRAGETOWER3F"]={ land=true },
 ["EMMIRAGETOWER4F"]={ land=true },
 ["EMMOSSDEEPCITY"]={ water=true, fishing=true },
 ["EMMTPYRE1F"]={ land=true },
 ["EMMTPYRE2F"]={ land=true },
 ["EMMTPYRE3F"]={ land=true },
 ["EMMTPYRE4F"]={ land=true },
 ["EMMTPYRE5F"]={ land=true },
 ["EMMTPYRE6F"]={ land=true },
 ["EMMTPYREEXTERIOR"]={ land=true },
 ["EMMTPYRESUMMIT"]={ land=true },
 ["EMNEWMAUVILLEENTRANCE"]={ land=true },
 ["EMNEWMAUVILLEINSIDE"]={ land=true },
 ["EMPACIFIDLOGTOWN"]={ water=true, fishing=true },
 ["EMPETALBURGCITY"]={ water=true, fishing=true },
 ["EMPETALBURGWOODS"]={ land=true },
 ["EMROUTE101"]={ land=true },
 ["EMROUTE102"]={ land=true, water=true, fishing=true },
 ["EMROUTE103"]={ land=true, water=true, fishing=true },
 ["EMROUTE104"]={ land=true, water=true, fishing=true },
 ["EMROUTE105"]={ water=true, fishing=true },
 ["EMROUTE106"]={ water=true, fishing=true },
 ["EMROUTE107"]={ water=true, fishing=true },
 ["EMROUTE108"]={ water=true, fishing=true },
 ["EMROUTE109"]={ water=true, fishing=true },
 ["EMROUTE110"]={ land=true, water=true, fishing=true },
 ["EMROUTE111"]={ land=true, water=true, fishing=true, rocks=true },
 ["EMROUTE112"]={ land=true },
 ["EMROUTE113"]={ land=true },
 ["EMROUTE114"]={ land=true, water=true, fishing=true, rocks=true },
 ["EMROUTE115"]={ land=true, water=true, fishing=true },
 ["EMROUTE116"]={ land=true },
 ["EMROUTE117"]={ land=true, water=true, fishing=true },
 ["EMROUTE118"]={ land=true, water=true, fishing=true },
 ["EMROUTE119"]={ land=true, water=true, fishing=true },
 ["EMROUTE120"]={ land=true, water=true, fishing=true },
 ["EMROUTE121"]={ land=true, water=true, fishing=true },
 ["EMROUTE122"]={ water=true, fishing=true },
 ["EMROUTE123"]={ land=true, water=true, fishing=true },
 ["EMROUTE124"]={ water=true, fishing=true },
 ["EMROUTE125"]={ water=true, fishing=true },
 ["EMROUTE126"]={ water=true, fishing=true },
 ["EMROUTE127"]={ water=true, fishing=true },
 ["EMROUTE128"]={ water=true, fishing=true },
 ["EMROUTE129"]={ water=true, fishing=true },
 ["EMROUTE130"]={ land=true, water=true, fishing=true },
 ["EMROUTE131"]={ water=true, fishing=true },
 ["EMROUTE132"]={ water=true, fishing=true },
 ["EMROUTE133"]={ water=true, fishing=true },
 ["EMROUTE134"]={ water=true, fishing=true },
 ["EMRUSTURFTUNNEL"]={ land=true },
 ["EMSAFARIZONENORTH"]={ land=true, rocks=true },
 ["EMSAFARIZONENORTHEAST"]={ land=true, rocks=true },
 ["EMSAFARIZONENORTHWEST"]={ land=true, water=true, fishing=true },
 ["EMSAFARIZONESOUTH"]={ land=true },
 ["EMSAFARIZONESOUTHEAST"]={ land=true, water=true, fishing=true },
 ["EMSAFARIZONESOUTHWEST"]={ land=true, water=true, fishing=true },
 ["EMSEAFLOORCAVERNENTRANCE"]={ water=true, fishing=true },
 ["EMSEAFLOORCAVERNROOM1"]={ land=true },
 ["EMSEAFLOORCAVERNROOM2"]={ land=true },
 ["EMSEAFLOORCAVERNROOM3"]={ land=true },
 ["EMSEAFLOORCAVERNROOM4"]={ land=true },
 ["EMSEAFLOORCAVERNROOM5"]={ land=true },
 ["EMSEAFLOORCAVERNROOM6"]={ land=true, water=true, fishing=true },
 ["EMSEAFLOORCAVERNROOM7"]={ land=true, water=true, fishing=true },
 ["EMSEAFLOORCAVERNROOM8"]={ land=true },
 ["EMSHOALCAVELOWTIDEENTRANCEROOM"]={ land=true, water=true, fishing=true },
 ["EMSHOALCAVELOWTIDEICEROOM"]={ land=true },
 ["EMSHOALCAVELOWTIDEINNERROOM"]={ land=true, water=true, fishing=true },
 ["EMSHOALCAVELOWTIDELOWERROOM"]={ land=true },
 ["EMSHOALCAVELOWTIDESTAIRSROOM"]={ land=true },
 ["EMSKYPILLAR1F"]={ land=true },
 ["EMSKYPILLAR3F"]={ land=true },
 ["EMSKYPILLAR5F"]={ land=true },
 ["EMSLATEPORTCITY"]={ water=true, fishing=true },
 ["EMSOOTOPOLISCITY"]={ water=true, fishing=true },
 ["EMUNDERWATERROUTE124"]={ water=true },
 ["EMUNDERWATERROUTE126"]={ water=true },
 ["EMVICTORYROAD1F"]={ land=true },
 ["EMVICTORYROADB1F"]={ land=true, rocks=true },
 ["EMVICTORYROADB2F"]={ land=true, water=true, fishing=true },
 ["FRCELADONCITY"]={ water=true, fishing=true },
 ["FRCERULEANCAVE1F"]={ land=true, water=true, fishing=true, rocks=true },
 ["FRCERULEANCAVE2F"]={ land=true, rocks=true },
 ["FRCERULEANCAVEB1F"]={ land=true, water=true, fishing=true, rocks=true },
 ["FRCERULEANCITY"]={ water=true, fishing=true },
 ["FRCINNABARISLAND"]={ water=true, fishing=true },
 ["FRDIGLETTSCAVEB1F"]={ land=true },
 ["FRFIVEISLAND"]={ water=true, fishing=true },
 ["FRFIVEISLANDLOSTCAVEROOM1"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM10"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM11"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM12"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM13"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM14"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM2"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM3"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM4"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM5"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM6"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM7"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM8"]={ land=true },
 ["FRFIVEISLANDLOSTCAVEROOM9"]={ land=true },
 ["FRFIVEISLANDMEADOW"]={ land=true, water=true, fishing=true },
 ["FRFIVEISLANDMEMORIALPILLAR"]={ land=true, water=true, fishing=true },
 ["FRFIVEISLANDRESORTGORGEOUS"]={ water=true, fishing=true },
 ["FRFIVEISLANDWATERLABYRINTH"]={ water=true, fishing=true },
 ["FRFOURISLAND"]={ water=true, fishing=true },
 ["FRFOURISLANDICEFALLCAVE1F"]={ land=true },
 ["FRFOURISLANDICEFALLCAVEB1F"]={ land=true },
 ["FRFOURISLANDICEFALLCAVEBACK"]={ land=true, water=true, fishing=true },
 ["FRFOURISLANDICEFALLCAVEENTRANCE"]={ land=true, water=true, fishing=true },
 ["FRFUCHSIACITY"]={ water=true, fishing=true },
 ["FRMTEMBEREXTERIOR"]={ land=true, rocks=true },
 ["FRMTEMBERRUBYPATH1F"]={ land=true, rocks=true },
 ["FRMTEMBERRUBYPATHB1F"]={ land=true, rocks=true },
 ["FRMTEMBERRUBYPATHB1FSTAIRS"]={ land=true, rocks=true },
 ["FRMTEMBERRUBYPATHB2F"]={ land=true, rocks=true },
 ["FRMTEMBERRUBYPATHB2FSTAIRS"]={ land=true, rocks=true },
 ["FRMTEMBERRUBYPATHB3F"]={ land=true, rocks=true },
 ["FRMTEMBERSUMMITPATH1F"]={ land=true },
 ["FRMTEMBERSUMMITPATH2F"]={ land=true, rocks=true },
 ["FRMTEMBERSUMMITPATH3F"]={ land=true },
 ["FRMTMOON1F"]={ land=true },
 ["FRMTMOONB1F"]={ land=true },
 ["FRMTMOONB2F"]={ land=true },
 ["FRPALLETTOWN"]={ water=true, fishing=true },
 ["FRPOKEMONMANSION1F"]={ land=true },
 ["FRPOKEMONMANSION2F"]={ land=true },
 ["FRPOKEMONMANSION3F"]={ land=true },
 ["FRPOKEMONMANSIONB1F"]={ land=true },
 ["FRPOKEMONTOWER3F"]={ land=true },
 ["FRPOKEMONTOWER4F"]={ land=true },
 ["FRPOKEMONTOWER5F"]={ land=true },
 ["FRPOKEMONTOWER6F"]={ land=true },
 ["FRPOKEMONTOWER7F"]={ land=true },
 ["FRPOWERPLANT"]={ land=true },
 ["FRROCKTUNNEL1F"]={ land=true },
 ["FRROCKTUNNELB1F"]={ land=true, rocks=true },
 ["FRROUTE1"]={ land=true },
 ["FRROUTE10"]={ land=true, water=true, fishing=true },
 ["FRROUTE11"]={ land=true, water=true, fishing=true },
 ["FRROUTE12"]={ land=true, water=true, fishing=true },
 ["FRROUTE13"]={ land=true, water=true, fishing=true },
 ["FRROUTE14"]={ land=true },
 ["FRROUTE15"]={ land=true },
 ["FRROUTE16"]={ land=true },
 ["FRROUTE17"]={ land=true },
 ["FRROUTE18"]={ land=true },
 ["FRROUTE19"]={ water=true, fishing=true },
 ["FRROUTE2"]={ land=true },
 ["FRROUTE20"]={ water=true, fishing=true },
 ["FRROUTE21NORTH"]={ land=true, water=true, fishing=true },
 ["FRROUTE21SOUTH"]={ land=true, water=true, fishing=true },
 ["FRROUTE22"]={ land=true, water=true, fishing=true },
 ["FRROUTE23"]={ land=true, water=true, fishing=true },
 ["FRROUTE24"]={ land=true, water=true, fishing=true },
 ["FRROUTE25"]={ land=true, water=true, fishing=true },
 ["FRROUTE3"]={ land=true },
 ["FRROUTE4"]={ land=true, water=true, fishing=true },
 ["FRROUTE5"]={ land=true },
 ["FRROUTE6"]={ land=true, water=true, fishing=true },
 ["FRROUTE7"]={ land=true },
 ["FRROUTE8"]={ land=true },
 ["FRROUTE9"]={ land=true },
 ["FRSAFARIZONECENTER"]={ land=true, water=true, fishing=true },
 ["FRSAFARIZONEEAST"]={ land=true, water=true, fishing=true },
 ["FRSAFARIZONENORTH"]={ land=true, water=true, fishing=true },
 ["FRSAFARIZONEWEST"]={ land=true, water=true, fishing=true },
 ["FRSEAFOAMISLANDS1F"]={ land=true },
 ["FRSEAFOAMISLANDSB1F"]={ land=true },
 ["FRSEAFOAMISLANDSB2F"]={ land=true },
 ["FRSEAFOAMISLANDSB3F"]={ land=true, water=true, fishing=true },
 ["FRSEAFOAMISLANDSB4F"]={ land=true, water=true, fishing=true },
 ["FRSEVENISLANDSEVAULTCANYON"]={ land=true, rocks=true },
 ["FRSEVENISLANDSEVAULTCANYONENTRANCE"]={ land=true },
 ["FRSEVENISLANDTANOBYRUINS"]={ water=true, fishing=true },
 ["FRSEVENISLANDTANOBYRUINSDILFORDCHAMBER"]={ land=true },
 ["FRSEVENISLANDTANOBYRUINSLIPTOOCHAMBER"]={ land=true },
 ["FRSEVENISLANDTANOBYRUINSMONEANCHAMBER"]={ land=true },
 ["FRSEVENISLANDTANOBYRUINSRIXYCHAMBER"]={ land=true },
 ["FRSEVENISLANDTANOBYRUINSSCUFIBCHAMBER"]={ land=true },
 ["FRSEVENISLANDTANOBYRUINSVIAPOISCHAMBER"]={ land=true },
 ["FRSEVENISLANDTANOBYRUINSWEEPTHCHAMBER"]={ land=true },
 ["FRSEVENISLANDTRAINERTOWER"]={ water=true, fishing=true },
 ["FRSIXISLANDALTERINGCAVE"]={ land=true },
 ["FRSIXISLANDGREENPATH"]={ water=true, fishing=true },
 ["FRSIXISLANDOUTCASTISLAND"]={ water=true, fishing=true },
 ["FRSIXISLANDPATTERNBUSH"]={ land=true },
 ["FRSIXISLANDRUINVALLEY"]={ land=true, water=true, fishing=true },
 ["FRSIXISLANDWATERPATH"]={ land=true, water=true, fishing=true },
 ["FRSSANNEEXTERIOR"]={ water=true, fishing=true },
 ["FRTHREEISLANDBERRYFOREST"]={ land=true, water=true, fishing=true },
 ["FRTHREEISLANDBONDBRIDGE"]={ land=true, water=true, fishing=true },
 ["FRTHREEISLANDPORT"]={ land=true },
 ["FRTWOISLANDCAPEBRINK"]={ land=true, water=true, fishing=true },
 ["FRVERMILIONCITY"]={ water=true, fishing=true },
 ["FRVICTORYROAD1F"]={ land=true },
 ["FRVICTORYROAD2F"]={ land=true },
 ["FRVICTORYROAD3F"]={ land=true },
 ["FRVIRIDIANCITY"]={ water=true, fishing=true },
 ["FRVIRIDIANFOREST"]={ land=true },
 ["SEVIIONEISLAND"]={ water=true, fishing=true },
 ["SEVIIONEISLANDKINDLEROAD"]={ land=true, water=true, fishing=true, rocks=true },
 ["SEVIIONEISLANDTREASUREBEACH"]={ land=true, water=true, fishing=true },
}
