-- Hoenn encounter profiles from Emerald USA native encounter tables.
-- Native residents are National numbers; later generations get additive habitat homes.
return {
  {
    fishing = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [129] = true,
        [72] = true,
        [73] = true,
      },
    },
    habitat = "meadow",
    hi = 35,
    hoenn = true,
    lo = 5,
    map = "EM_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [72] = true,
        [73] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [129] = true,
        [72] = true,
        [73] = true,
      },
    },
    habitat = "meadow",
    hi = 35,
    hoenn = true,
    lo = 5,
    map = "EM_ABANDONED_SHIP_ROOMS_B1F",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [72] = true,
        [73] = true,
      },
    },
  },
  {
    habitat = "cave",
    hi = 29,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 29,
      lo = 3,
      native = {
        [179] = true,
        [190] = true,
        [204] = true,
        [213] = true,
        [216] = true,
        [228] = true,
        [234] = true,
        [235] = true,
        [41] = true,
      },
    },
    lo = 3,
    map = "EM_ALTERING_CAVE",
  },
  {
    habitat = "safari",
    hi = 70,
    hoenn = true,
    land = {
      any = true,
      habitat = "safari",
      hi = 70,
      lo = 40,
      native = {
        [235] = true,
      },
    },
    lo = 40,
    map = "EM_ARTISAN_CAVE_1F",
    postgame = true,
  },
  {
    habitat = "safari",
    hi = 70,
    hoenn = true,
    land = {
      any = true,
      habitat = "safari",
      hi = 70,
      lo = 40,
      native = {
        [235] = true,
      },
    },
    lo = 40,
    map = "EM_ARTISAN_CAVE_B1F",
    postgame = true,
  },
  {
    habitat = "cave",
    hi = 36,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 30,
      native = {
        [302] = true,
        [41] = true,
        [42] = true,
      },
    },
    lo = 30,
    map = "EM_CAVE_OF_ORIGIN_1F",
  },
  {
    habitat = "cave",
    hi = 36,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 28,
      native = {
        [41] = true,
        [42] = true,
      },
    },
    lo = 28,
    map = "EM_CAVE_OF_ORIGIN_ENTRANCE",
  },
  {
    habitat = "cave",
    hi = 36,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 30,
      native = {
        [302] = true,
        [41] = true,
        [42] = true,
      },
    },
    lo = 30,
    map = "EM_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1",
  },
  {
    habitat = "cave",
    hi = 36,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 30,
      native = {
        [302] = true,
        [41] = true,
        [42] = true,
      },
    },
    lo = 30,
    map = "EM_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2",
  },
  {
    habitat = "cave",
    hi = 36,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 30,
      native = {
        [302] = true,
        [41] = true,
        [42] = true,
      },
    },
    lo = 30,
    map = "EM_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3",
  },
  {
    habitat = "cave",
    hi = 60,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 60,
      lo = 35,
      native = {
        [132] = true,
        [293] = true,
        [294] = true,
      },
    },
    lo = 35,
    map = "EM_DESERT_UNDERPASS",
    postgame = true,
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_DEWFORD_TOWN",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [222] = true,
        [320] = true,
        [370] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_EVER_GRANDE_CITY",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    habitat = "volcanic",
    hi = 16,
    hoenn = true,
    land = {
      habitat = "volcanic",
      hi = 16,
      lo = 14,
      native = {
        [109] = true,
        [218] = true,
        [322] = true,
        [324] = true,
        [66] = true,
        [88] = true,
      },
    },
    lo = 14,
    map = "EM_FIERY_PATH",
  },
  {
    habitat = "cave",
    hi = 10,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 10,
      lo = 6,
      native = {
        [296] = true,
        [41] = true,
        [63] = true,
        [74] = true,
      },
    },
    lo = 6,
    map = "EM_GRANITE_CAVE_1F",
  },
  {
    habitat = "cave",
    hi = 11,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 11,
      lo = 9,
      native = {
        [296] = true,
        [302] = true,
        [304] = true,
        [41] = true,
        [63] = true,
      },
    },
    lo = 9,
    map = "EM_GRANITE_CAVE_B1F",
  },
  {
    habitat = "cave",
    hi = 20,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 12,
      lo = 10,
      native = {
        [302] = true,
        [304] = true,
        [41] = true,
        [63] = true,
      },
    },
    lo = 5,
    map = "EM_GRANITE_CAVE_B2F",
    rocks = {
      habitat = "cave",
      hi = 20,
      lo = 5,
      native = {
        [299] = true,
        [74] = true,
      },
    },
  },
  {
    habitat = "cave",
    hi = 10,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 10,
      lo = 6,
      native = {
        [296] = true,
        [304] = true,
        [41] = true,
        [63] = true,
      },
    },
    lo = 6,
    map = "EM_GRANITE_CAVE_STEVENS_ROOM",
  },
  {
    habitat = "volcanic",
    hi = 22,
    hoenn = true,
    land = {
      habitat = "volcanic",
      hi = 22,
      lo = 20,
      native = {
        [322] = true,
        [325] = true,
        [66] = true,
      },
    },
    lo = 20,
    map = "EM_JAGGED_PASS",
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [120] = true,
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_LILYCOVE_CITY",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    habitat = "volcanic",
    hi = 33,
    hoenn = true,
    land = {
      habitat = "volcanic",
      hi = 33,
      lo = 27,
      native = {
        [324] = true,
        [74] = true,
        [75] = true,
      },
    },
    lo = 27,
    map = "EM_MAGMA_HIDEOUT_1F",
  },
  {
    habitat = "volcanic",
    hi = 33,
    hoenn = true,
    land = {
      habitat = "volcanic",
      hi = 33,
      lo = 27,
      native = {
        [324] = true,
        [74] = true,
        [75] = true,
      },
    },
    lo = 27,
    map = "EM_MAGMA_HIDEOUT_2F_1R",
  },
  {
    habitat = "volcanic",
    hi = 33,
    hoenn = true,
    land = {
      habitat = "volcanic",
      hi = 33,
      lo = 27,
      native = {
        [324] = true,
        [74] = true,
        [75] = true,
      },
    },
    lo = 27,
    map = "EM_MAGMA_HIDEOUT_2F_2R",
  },
  {
    habitat = "volcanic",
    hi = 33,
    hoenn = true,
    land = {
      habitat = "volcanic",
      hi = 33,
      lo = 27,
      native = {
        [324] = true,
        [74] = true,
        [75] = true,
      },
    },
    lo = 27,
    map = "EM_MAGMA_HIDEOUT_2F_3R",
  },
  {
    habitat = "volcanic",
    hi = 33,
    hoenn = true,
    land = {
      habitat = "volcanic",
      hi = 33,
      lo = 27,
      native = {
        [324] = true,
        [74] = true,
        [75] = true,
      },
    },
    lo = 27,
    map = "EM_MAGMA_HIDEOUT_3F_1R",
  },
  {
    habitat = "volcanic",
    hi = 33,
    hoenn = true,
    land = {
      habitat = "volcanic",
      hi = 33,
      lo = 27,
      native = {
        [324] = true,
        [74] = true,
        [75] = true,
      },
    },
    lo = 27,
    map = "EM_MAGMA_HIDEOUT_3F_2R",
  },
  {
    habitat = "volcanic",
    hi = 33,
    hoenn = true,
    land = {
      habitat = "volcanic",
      hi = 33,
      lo = 27,
      native = {
        [324] = true,
        [74] = true,
        [75] = true,
      },
    },
    lo = 27,
    map = "EM_MAGMA_HIDEOUT_3F_3R",
  },
  {
    habitat = "volcanic",
    hi = 33,
    hoenn = true,
    land = {
      habitat = "volcanic",
      hi = 33,
      lo = 27,
      native = {
        [324] = true,
        [74] = true,
        [75] = true,
      },
    },
    lo = 27,
    map = "EM_MAGMA_HIDEOUT_4F",
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [118] = true,
        [129] = true,
        [339] = true,
      },
    },
    habitat = "cave",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 20,
      lo = 14,
      native = {
        [338] = true,
        [41] = true,
      },
    },
    lo = 5,
    map = "EM_METEOR_FALLS_1F_1R",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [338] = true,
        [41] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [118] = true,
        [129] = true,
        [339] = true,
        [340] = true,
      },
    },
    habitat = "cave",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 40,
      lo = 33,
      native = {
        [338] = true,
        [42] = true,
      },
    },
    lo = 5,
    map = "EM_METEOR_FALLS_1F_2R",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [338] = true,
        [42] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [118] = true,
        [129] = true,
        [339] = true,
        [340] = true,
      },
    },
    habitat = "cave",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 40,
      lo = 33,
      native = {
        [338] = true,
        [42] = true,
      },
    },
    lo = 5,
    map = "EM_METEOR_FALLS_B1F_1R",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [338] = true,
        [42] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [118] = true,
        [129] = true,
        [339] = true,
        [340] = true,
      },
    },
    habitat = "cave",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 40,
      lo = 25,
      native = {
        [338] = true,
        [371] = true,
        [42] = true,
      },
    },
    lo = 5,
    map = "EM_METEOR_FALLS_B1F_2R",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [338] = true,
        [42] = true,
      },
    },
  },
  {
    habitat = "cave",
    hi = 55,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 55,
      lo = 33,
      native = {
        [338] = true,
        [42] = true,
      },
    },
    lo = 33,
    map = "EM_METEOR_FALLS_STEVENS_CAVE",
  },
  {
    habitat = "cave",
    hi = 24,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 24,
      lo = 20,
      native = {
        [27] = true,
        [328] = true,
      },
    },
    lo = 20,
    map = "EM_MIRAGE_TOWER_1F",
  },
  {
    habitat = "cave",
    hi = 24,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 24,
      lo = 20,
      native = {
        [27] = true,
        [328] = true,
      },
    },
    lo = 20,
    map = "EM_MIRAGE_TOWER_2F",
  },
  {
    habitat = "cave",
    hi = 24,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 24,
      lo = 20,
      native = {
        [27] = true,
        [328] = true,
      },
    },
    lo = 20,
    map = "EM_MIRAGE_TOWER_3F",
  },
  {
    habitat = "cave",
    hi = 24,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 24,
      lo = 20,
      native = {
        [27] = true,
        [328] = true,
      },
    },
    lo = 20,
    map = "EM_MIRAGE_TOWER_4F",
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_MOSSDEEP_CITY",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    habitat = "ghost",
    hi = 29,
    hoenn = true,
    land = {
      habitat = "ghost",
      hi = 29,
      lo = 22,
      native = {
        [353] = true,
      },
    },
    lo = 22,
    map = "EM_MT_PYRE_1F",
  },
  {
    habitat = "ghost",
    hi = 29,
    hoenn = true,
    land = {
      habitat = "ghost",
      hi = 29,
      lo = 22,
      native = {
        [353] = true,
      },
    },
    lo = 22,
    map = "EM_MT_PYRE_2F",
  },
  {
    habitat = "ghost",
    hi = 29,
    hoenn = true,
    land = {
      habitat = "ghost",
      hi = 29,
      lo = 22,
      native = {
        [353] = true,
      },
    },
    lo = 22,
    map = "EM_MT_PYRE_3F",
  },
  {
    habitat = "ghost",
    hi = 29,
    hoenn = true,
    land = {
      habitat = "ghost",
      hi = 29,
      lo = 22,
      native = {
        [353] = true,
        [355] = true,
      },
    },
    lo = 22,
    map = "EM_MT_PYRE_4F",
  },
  {
    habitat = "ghost",
    hi = 29,
    hoenn = true,
    land = {
      habitat = "ghost",
      hi = 29,
      lo = 22,
      native = {
        [353] = true,
        [355] = true,
      },
    },
    lo = 22,
    map = "EM_MT_PYRE_5F",
  },
  {
    habitat = "ghost",
    hi = 29,
    hoenn = true,
    land = {
      habitat = "ghost",
      hi = 29,
      lo = 22,
      native = {
        [353] = true,
        [355] = true,
      },
    },
    lo = 22,
    map = "EM_MT_PYRE_6F",
  },
  {
    habitat = "ghost",
    hi = 29,
    hoenn = true,
    land = {
      habitat = "ghost",
      hi = 29,
      lo = 25,
      native = {
        [278] = true,
        [353] = true,
        [37] = true,
      },
    },
    lo = 25,
    map = "EM_MT_PYRE_EXTERIOR",
  },
  {
    habitat = "ghost",
    hi = 30,
    hoenn = true,
    land = {
      habitat = "ghost",
      hi = 30,
      lo = 24,
      native = {
        [353] = true,
        [355] = true,
        [358] = true,
      },
    },
    lo = 24,
    map = "EM_MT_PYRE_SUMMIT",
  },
  {
    habitat = "electric",
    hi = 26,
    hoenn = true,
    land = {
      habitat = "electric",
      hi = 26,
      lo = 22,
      native = {
        [100] = true,
        [81] = true,
      },
    },
    lo = 22,
    map = "EM_NEW_MAUVILLE_ENTRANCE",
  },
  {
    habitat = "electric",
    hi = 26,
    hoenn = true,
    land = {
      habitat = "electric",
      hi = 26,
      lo = 22,
      native = {
        [100] = true,
        [101] = true,
        [81] = true,
        [82] = true,
      },
    },
    lo = 22,
    map = "EM_NEW_MAUVILLE_INSIDE",
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_PACIFIDLOG_TOWN",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "freshwater",
      hi = 45,
      lo = 5,
      native = {
        [118] = true,
        [129] = true,
        [341] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_PETALBURG_CITY",
    water = {
      habitat = "freshwater",
      hi = 35,
      lo = 5,
      native = {
        [183] = true,
      },
    },
  },
  {
    habitat = "forest",
    hi = 6,
    hoenn = true,
    land = {
      habitat = "forest",
      hi = 6,
      lo = 5,
      native = {
        [261] = true,
        [265] = true,
        [266] = true,
        [268] = true,
        [276] = true,
        [285] = true,
        [287] = true,
      },
    },
    lo = 5,
    map = "EM_PETALBURG_WOODS",
  },
  {
    featured = {
      252,
      255,
      258,
    },
    habitat = "meadow",
    hi = 3,
    hoenn = true,
    land = {
      habitat = "meadow",
      hi = 3,
      lo = 2,
      native = {
        [261] = true,
        [263] = true,
        [265] = true,
      },
    },
    lo = 2,
    map = "EM_ROUTE101",
  },
  {
    fishing = {
      habitat = "freshwater",
      hi = 45,
      lo = 5,
      native = {
        [118] = true,
        [129] = true,
        [341] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "meadow",
      hi = 4,
      lo = 3,
      native = {
        [261] = true,
        [263] = true,
        [265] = true,
        [270] = true,
        [273] = true,
        [280] = true,
      },
    },
    lo = 3,
    map = "EM_ROUTE102",
    water = {
      habitat = "freshwater",
      hi = 35,
      lo = 5,
      native = {
        [118] = true,
        [183] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "meadow",
      hi = 4,
      lo = 2,
      native = {
        [261] = true,
        [263] = true,
        [278] = true,
      },
    },
    lo = 2,
    map = "EM_ROUTE103",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
      },
    },
    habitat = "forest",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "forest",
      hi = 5,
      lo = 3,
      native = {
        [183] = true,
        [261] = true,
        [265] = true,
        [276] = true,
        [278] = true,
      },
    },
    lo = 3,
    map = "EM_ROUTE104",
    water = {
      habitat = "sea",
      hi = 30,
      lo = 10,
      native = {
        [278] = true,
        [279] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE105",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE106",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE107",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE108",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE109",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "electric",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "electric",
      hi = 13,
      lo = 12,
      native = {
        [261] = true,
        [278] = true,
        [309] = true,
        [311] = true,
        [312] = true,
        [316] = true,
        [43] = true,
      },
    },
    lo = 5,
    map = "EM_ROUTE110",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "freshwater",
      hi = 45,
      lo = 5,
      native = {
        [118] = true,
        [129] = true,
        [339] = true,
      },
    },
    habitat = "cave",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 22,
      lo = 19,
      native = {
        [27] = true,
        [328] = true,
        [331] = true,
        [343] = true,
      },
    },
    lo = 5,
    map = "EM_ROUTE111",
    rocks = {
      habitat = "cave",
      hi = 20,
      lo = 5,
      native = {
        [74] = true,
      },
    },
    water = {
      habitat = "freshwater",
      hi = 35,
      lo = 5,
      native = {
        [118] = true,
        [183] = true,
      },
    },
  },
  {
    habitat = "volcanic",
    hi = 16,
    hoenn = true,
    land = {
      habitat = "volcanic",
      hi = 16,
      lo = 14,
      native = {
        [183] = true,
        [322] = true,
      },
    },
    lo = 14,
    map = "EM_ROUTE112",
  },
  {
    habitat = "meadow",
    hi = 16,
    hoenn = true,
    land = {
      habitat = "meadow",
      hi = 16,
      lo = 14,
      native = {
        [218] = true,
        [227] = true,
        [327] = true,
      },
    },
    lo = 14,
    map = "EM_ROUTE113",
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [118] = true,
        [129] = true,
        [339] = true,
      },
    },
    habitat = "forest",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "forest",
      hi = 18,
      lo = 15,
      native = {
        [270] = true,
        [271] = true,
        [274] = true,
        [333] = true,
        [336] = true,
      },
    },
    lo = 5,
    map = "EM_ROUTE114",
    rocks = {
      habitat = "forest",
      hi = 20,
      lo = 5,
      native = {
        [74] = true,
      },
    },
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [118] = true,
        [183] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "meadow",
      hi = 26,
      lo = 23,
      native = {
        [276] = true,
        [277] = true,
        [278] = true,
        [333] = true,
        [39] = true,
      },
    },
    lo = 5,
    map = "EM_ROUTE115",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    habitat = "meadow",
    hi = 8,
    hoenn = true,
    land = {
      habitat = "meadow",
      hi = 8,
      lo = 6,
      native = {
        [261] = true,
        [276] = true,
        [290] = true,
        [293] = true,
        [300] = true,
        [63] = true,
      },
    },
    lo = 6,
    map = "EM_ROUTE116",
  },
  {
    fishing = {
      habitat = "freshwater",
      hi = 45,
      lo = 5,
      native = {
        [118] = true,
        [129] = true,
        [341] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "meadow",
      hi = 14,
      lo = 13,
      native = {
        [183] = true,
        [261] = true,
        [273] = true,
        [313] = true,
        [314] = true,
        [43] = true,
      },
    },
    lo = 5,
    map = "EM_ROUTE117",
    water = {
      habitat = "freshwater",
      hi = 35,
      lo = 5,
      native = {
        [118] = true,
        [183] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [318] = true,
        [319] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "meadow",
      hi = 27,
      lo = 24,
      native = {
        [263] = true,
        [264] = true,
        [278] = true,
        [309] = true,
        [310] = true,
        [352] = true,
      },
    },
    lo = 5,
    map = "EM_ROUTE118",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "freshwater",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [318] = true,
        [72] = true,
      },
    },
    habitat = "forest",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "forest",
      hi = 27,
      lo = 24,
      native = {
        [263] = true,
        [264] = true,
        [352] = true,
        [357] = true,
        [43] = true,
      },
    },
    lo = 5,
    map = "EM_ROUTE119",
    water = {
      habitat = "freshwater",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "freshwater",
      hi = 45,
      lo = 5,
      native = {
        [118] = true,
        [129] = true,
        [339] = true,
      },
    },
    habitat = "forest",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "forest",
      hi = 27,
      lo = 25,
      native = {
        [183] = true,
        [261] = true,
        [262] = true,
        [273] = true,
        [352] = true,
        [359] = true,
        [43] = true,
      },
    },
    lo = 5,
    map = "EM_ROUTE120",
    water = {
      habitat = "freshwater",
      hi = 35,
      lo = 5,
      native = {
        [118] = true,
        [183] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "meadow",
      hi = 28,
      lo = 25,
      native = {
        [261] = true,
        [262] = true,
        [278] = true,
        [352] = true,
        [353] = true,
        [43] = true,
        [44] = true,
      },
    },
    lo = 5,
    map = "EM_ROUTE121",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE122",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "meadow",
      hi = 28,
      lo = 25,
      native = {
        [261] = true,
        [262] = true,
        [278] = true,
        [352] = true,
        [353] = true,
        [43] = true,
        [44] = true,
      },
    },
    lo = 5,
    map = "EM_ROUTE123",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE124",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE125",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE126",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE127",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [222] = true,
        [320] = true,
        [370] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE128",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE129",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [321] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 50,
    hoenn = true,
    land = {
      habitat = "meadow",
      hi = 50,
      lo = 5,
      native = {
        [360] = true,
      },
    },
    lo = 5,
    map = "EM_ROUTE130",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE131",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [116] = true,
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE132",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [116] = true,
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE133",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [116] = true,
        [129] = true,
        [319] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_ROUTE134",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    habitat = "cave",
    hi = 8,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 8,
      lo = 5,
      native = {
        [293] = true,
      },
    },
    lo = 5,
    map = "EM_RUSTURF_TUNNEL",
  },
  {
    habitat = "safari",
    hi = 31,
    hoenn = true,
    land = {
      habitat = "safari",
      hi = 31,
      lo = 27,
      native = {
        [177] = true,
        [178] = true,
        [214] = true,
        [231] = true,
        [43] = true,
        [44] = true,
      },
    },
    lo = 5,
    map = "EM_SAFARI_ZONE_NORTH",
    rocks = {
      habitat = "safari",
      hi = 30,
      lo = 5,
      native = {
        [74] = true,
      },
    },
  },
  {
    habitat = "safari",
    hi = 40,
    hoenn = true,
    land = {
      habitat = "safari",
      hi = 40,
      lo = 33,
      native = {
        [163] = true,
        [165] = true,
        [190] = true,
        [191] = true,
        [204] = true,
        [216] = true,
        [228] = true,
        [241] = true,
      },
    },
    lo = 20,
    map = "EM_SAFARI_ZONE_NORTHEAST",
    rocks = {
      habitat = "safari",
      hi = 40,
      lo = 20,
      native = {
        [213] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "freshwater",
      hi = 40,
      lo = 5,
      native = {
        [118] = true,
        [119] = true,
        [129] = true,
      },
    },
    habitat = "safari",
    hi = 40,
    hoenn = true,
    land = {
      habitat = "safari",
      hi = 31,
      lo = 27,
      native = {
        [111] = true,
        [127] = true,
        [43] = true,
        [44] = true,
        [84] = true,
        [85] = true,
      },
    },
    lo = 5,
    map = "EM_SAFARI_ZONE_NORTHWEST",
    water = {
      habitat = "freshwater",
      hi = 40,
      lo = 20,
      native = {
        [54] = true,
        [55] = true,
      },
    },
  },
  {
    habitat = "safari",
    hi = 29,
    hoenn = true,
    land = {
      habitat = "safari",
      hi = 29,
      lo = 25,
      native = {
        [177] = true,
        [202] = true,
        [203] = true,
        [25] = true,
        [43] = true,
        [44] = true,
        [84] = true,
      },
    },
    lo = 25,
    map = "EM_SAFARI_ZONE_SOUTH",
  },
  {
    fishing = {
      habitat = "sea",
      hi = 40,
      lo = 25,
      native = {
        [118] = true,
        [129] = true,
        [223] = true,
        [224] = true,
      },
    },
    habitat = "safari",
    hi = 40,
    hoenn = true,
    land = {
      habitat = "safari",
      hi = 40,
      lo = 33,
      native = {
        [163] = true,
        [167] = true,
        [179] = true,
        [190] = true,
        [191] = true,
        [207] = true,
        [209] = true,
        [234] = true,
      },
    },
    lo = 25,
    map = "EM_SAFARI_ZONE_SOUTHEAST",
    water = {
      habitat = "sea",
      hi = 40,
      lo = 25,
      native = {
        [183] = true,
        [194] = true,
        [195] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "freshwater",
      hi = 40,
      lo = 5,
      native = {
        [118] = true,
        [119] = true,
        [129] = true,
      },
    },
    habitat = "safari",
    hi = 40,
    hoenn = true,
    land = {
      habitat = "safari",
      hi = 29,
      lo = 25,
      native = {
        [177] = true,
        [202] = true,
        [203] = true,
        [25] = true,
        [43] = true,
        [44] = true,
        [84] = true,
      },
    },
    lo = 5,
    map = "EM_SAFARI_ZONE_SOUTHWEST",
    water = {
      habitat = "freshwater",
      hi = 35,
      lo = 20,
      native = {
        [54] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "cave",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_SEAFLOOR_CAVERN_ENTRANCE",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [41] = true,
        [42] = true,
        [72] = true,
      },
    },
  },
  {
    habitat = "cave",
    hi = 36,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 28,
      native = {
        [41] = true,
        [42] = true,
      },
    },
    lo = 28,
    map = "EM_SEAFLOOR_CAVERN_ROOM1",
  },
  {
    habitat = "cave",
    hi = 36,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 28,
      native = {
        [41] = true,
        [42] = true,
      },
    },
    lo = 28,
    map = "EM_SEAFLOOR_CAVERN_ROOM2",
  },
  {
    habitat = "cave",
    hi = 36,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 28,
      native = {
        [41] = true,
        [42] = true,
      },
    },
    lo = 28,
    map = "EM_SEAFLOOR_CAVERN_ROOM3",
  },
  {
    habitat = "cave",
    hi = 36,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 28,
      native = {
        [41] = true,
        [42] = true,
      },
    },
    lo = 28,
    map = "EM_SEAFLOOR_CAVERN_ROOM4",
  },
  {
    habitat = "cave",
    hi = 36,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 28,
      native = {
        [41] = true,
        [42] = true,
      },
    },
    lo = 28,
    map = "EM_SEAFLOOR_CAVERN_ROOM5",
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "cave",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 28,
      native = {
        [41] = true,
        [42] = true,
      },
    },
    lo = 5,
    map = "EM_SEAFLOOR_CAVERN_ROOM6",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [41] = true,
        [42] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "cave",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 28,
      native = {
        [41] = true,
        [42] = true,
      },
    },
    lo = 5,
    map = "EM_SEAFLOOR_CAVERN_ROOM7",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [41] = true,
        [42] = true,
        [72] = true,
      },
    },
  },
  {
    habitat = "cave",
    hi = 36,
    hoenn = true,
    land = {
      habitat = "cave",
      hi = 36,
      lo = 28,
      native = {
        [41] = true,
        [42] = true,
      },
    },
    lo = 28,
    map = "EM_SEAFLOOR_CAVERN_ROOM8",
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "ice",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "ice",
      hi = 32,
      lo = 26,
      native = {
        [363] = true,
        [41] = true,
        [42] = true,
      },
    },
    lo = 5,
    map = "EM_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [363] = true,
        [41] = true,
        [72] = true,
      },
    },
  },
  {
    habitat = "ice",
    hi = 32,
    hoenn = true,
    land = {
      habitat = "ice",
      hi = 32,
      lo = 26,
      native = {
        [361] = true,
        [363] = true,
        [41] = true,
        [42] = true,
      },
    },
    lo = 26,
    map = "EM_SHOAL_CAVE_LOW_TIDE_ICE_ROOM",
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "ice",
    hi = 45,
    hoenn = true,
    land = {
      habitat = "ice",
      hi = 32,
      lo = 26,
      native = {
        [363] = true,
        [41] = true,
        [42] = true,
      },
    },
    lo = 5,
    map = "EM_SHOAL_CAVE_LOW_TIDE_INNER_ROOM",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [363] = true,
        [41] = true,
        [72] = true,
      },
    },
  },
  {
    habitat = "ice",
    hi = 32,
    hoenn = true,
    land = {
      habitat = "ice",
      hi = 32,
      lo = 26,
      native = {
        [363] = true,
        [41] = true,
        [42] = true,
      },
    },
    lo = 26,
    map = "EM_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM",
  },
  {
    habitat = "ice",
    hi = 32,
    hoenn = true,
    land = {
      habitat = "ice",
      hi = 32,
      lo = 26,
      native = {
        [363] = true,
        [41] = true,
        [42] = true,
      },
    },
    lo = 26,
    map = "EM_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM",
  },
  {
    habitat = "ghost",
    hi = 38,
    hoenn = true,
    land = {
      habitat = "ghost",
      hi = 38,
      lo = 33,
      native = {
        [302] = true,
        [344] = true,
        [354] = true,
        [42] = true,
      },
    },
    lo = 33,
    map = "EM_SKY_PILLAR_1F",
  },
  {
    habitat = "ghost",
    hi = 38,
    hoenn = true,
    land = {
      habitat = "ghost",
      hi = 38,
      lo = 33,
      native = {
        [302] = true,
        [344] = true,
        [354] = true,
        [42] = true,
      },
    },
    lo = 33,
    map = "EM_SKY_PILLAR_3F",
  },
  {
    habitat = "ghost",
    hi = 39,
    hoenn = true,
    land = {
      habitat = "ghost",
      hi = 39,
      lo = 33,
      native = {
        [302] = true,
        [334] = true,
        [344] = true,
        [354] = true,
        [42] = true,
      },
    },
    lo = 33,
    map = "EM_SKY_PILLAR_5F",
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [320] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_SLATEPORT_CITY",
    water = {
      habitat = "sea",
      hi = 35,
      lo = 5,
      native = {
        [278] = true,
        [279] = true,
        [72] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "freshwater",
      hi = 45,
      lo = 5,
      native = {
        [129] = true,
        [130] = true,
        [72] = true,
      },
    },
    habitat = "meadow",
    hi = 45,
    hoenn = true,
    lo = 5,
    map = "EM_SOOTOPOLIS_CITY",
    water = {
      habitat = "freshwater",
      hi = 35,
      lo = 5,
      native = {
        [129] = true,
      },
    },
  },
  {
    habitat = "meadow",
    hi = 50,
    hoenn = true,
    lo = 20,
    map = "EM_UNDERWATER_ROUTE124",
    underwater = true,
    water = {
      habitat = "sea",
      hi = 50,
      lo = 20,
      native = {
        [170] = true,
        [366] = true,
        [369] = true,
      },
    },
  },
  {
    habitat = "meadow",
    hi = 50,
    hoenn = true,
    lo = 20,
    map = "EM_UNDERWATER_ROUTE126",
    underwater = true,
    water = {
      habitat = "sea",
      hi = 50,
      lo = 20,
      native = {
        [170] = true,
        [366] = true,
        [369] = true,
      },
    },
  },
  {
    habitat = "safari",
    hi = 55,
    hoenn = true,
    land = {
      habitat = "safari",
      hi = 55,
      lo = 36,
      native = {
        [293] = true,
        [294] = true,
        [296] = true,
        [297] = true,
        [304] = true,
        [305] = true,
        [41] = true,
        [42] = true,
      },
    },
    lo = 36,
    map = "EM_VICTORY_ROAD_1F",
  },
  {
    habitat = "safari",
    hi = 55,
    hoenn = true,
    land = {
      habitat = "safari",
      hi = 55,
      lo = 38,
      native = {
        [297] = true,
        [303] = true,
        [305] = true,
        [42] = true,
      },
    },
    lo = 30,
    map = "EM_VICTORY_ROAD_B1F",
    rocks = {
      habitat = "safari",
      hi = 40,
      lo = 30,
      native = {
        [74] = true,
        [75] = true,
      },
    },
  },
  {
    fishing = {
      habitat = "sea",
      hi = 45,
      lo = 5,
      native = {
        [118] = true,
        [129] = true,
        [339] = true,
        [340] = true,
      },
    },
    habitat = "safari",
    hi = 55,
    hoenn = true,
    land = {
      habitat = "safari",
      hi = 55,
      lo = 40,
      native = {
        [302] = true,
        [303] = true,
        [305] = true,
        [42] = true,
      },
    },
    lo = 5,
    map = "EM_VICTORY_ROAD_B2F",
    water = {
      habitat = "sea",
      hi = 40,
      lo = 25,
      native = {
        [42] = true,
      },
    },
  },
}
