"""Called by build_encounter_guides.py; all-games behavior and habitat index."""
roster_lua=LuaRuntime(unpack_returned_tuples=True).execute((root/'encounters/roster.lua').read_text())
roster_rows=[dict(row.items()) for _,row in roster_lua.items()]
for row in roster_rows:
    row['habitat']={90:'sea',91:'sea',131:'sea',602:'freshwater',603:'freshwater',604:'freshwater'}.get(row['id'],row['habitat'])
data=json.dumps(roster_rows,separators=(',',':')).replace('</','<\\/')
companion='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>1025Dex 1.2.14 — All Games Encounter Companion</title><style>
body{font:16px/1.6 system-ui,sans-serif;background:#101722;color:#e8eef8;margin:0}main{max-width:1050px;margin:auto;padding:36px 24px}h1,h2{line-height:1.2}h2{margin-top:36px}p{max-width:85ch}a{color:#8ec9ff}strong{color:#a8e0c6}.note{background:#192738;border-left:4px solid #8ec9ff;padding:16px}input{background:#192738;color:#fff;border:1px solid #54708a;border-radius:8px;padding:12px;width:95%;font:inherit}table{border-collapse:collapse;width:100%;margin-top:18px}th,td{text-align:left;padding:10px;border-bottom:1px solid #304253}th{background:#192738}small{color:#a9b8cc}.table{overflow:auto}footer{margin-top:36px;color:#a9b8cc}</style><main>
<small>1025Dex 1.2.14 · Offline encounter companion</small><h1>All eleven games, one National roster</h1>
<p>Red, Blue, Yellow, Gold, Silver, Crystal, Ruby, Sapphire, FireRed, LeafGreen and Emerald. Requires Gen1Recomp 0.3.54 or later. Compatible with Hoennto 0.2.0.</p>
<h2>Red / Blue / Yellow and Gold / Silver / Crystal</h2>
<p>The cartridge rolls first. <strong>50% of successful ordinary rolls retain their exact native species and level.</strong> The remaining half can choose added species from up to two deterministic habitat homes per species. WILD GENS filters these additions; native Game Boy residents remain available with every setting. If no eligible addition exists, the native result stays.</p>
<p>Native encounter rates, morning/day/night slots, swarm substitutions, failed fishing bites and rod restrictions remain active. Fishing additions use the area's declared Surf habitat. Maps without a Surf habitat keep their original fishing pool. Bug Contest, scripted wilds, roamers, Headbutt and Rock Smash retain their original behavior.</p>
<p>Forest species use forest areas; fish use suitable fresh or sea water. Safari species also use mature meadow or forest routes. Electric species can use mature meadows; ghosts and volcanic species can use suitable late caves. Ice species use icy areas. Early areas exclude evolved and special additions. Added legendary and Ultra Beast homes require that cartridge's League clear.</p>
<p>Additions have relative weights of 100 for ordinary species, 5 for evolved species with catch rate 45 or less, and 1 for legendary or Ultra Beast additions. These are shared weights within the added half, not individual encounter percentages. After the League, late mountain, icy, Safari and Route 23/26/27/28 habitats may support added species up to level 70; during the story additions use the native area ceiling. retained native rolls still use exact cartridge levels.</p>
<h2>Ruby / Sapphire</h2><p>Each edition reads its own imported live grass, Surf, fishing and Rock Smash tables. It retains their native species and level ranges while assigning habitat additions. Route 119's special Feebas metadata is included. The Ruby table guide was generated from the supplied Ruby ROM. Sapphire's native rows are read at runtime; this release does not substitute Ruby or Emerald rows for them.</p>
<h2>FireRed / LeafGreen and Emerald</h2><p>The detailed HTML guides cover the existing native-preserving pools and all seventeen WILD GENS settings. Route 3 Jigglypuff remains available. Routes 4, 9, 10, 11 and 22 retain their repaired pools. Shellder now has a Hoenn campaign home, so both FireRed + Emerald and LeafGreen + Emerald cover all 1,025 species.</p>
<h2>Hoennto travel and storage</h2><p>All games register the same National species identities. Hoennto keeps each cartridge's story, dex and native state, and converts the shared collection. 1025Dex expands storage to 52 boxes of 20 in Gen 1/2 and 36 boxes of 30 in Gen 3, then fills those extra boxes during travel. Unsupported moves, held items, mail and Gen 1 eggs still follow Hoennto's reserve rules.</p>
<p>Yellow's native voiced Pikachu clips remain active. Other cries use exact National-number assets. Native battle mechanics and generation-specific stat shapes remain those of the destination cartridge.</p>
<div class="note">The index below lists added-species habitat and evolution thresholds. It is <strong>not an exact route table</strong>. Game Boy and Sapphire native tables depend on the imported cartridge. Wild additions require an actual encounter channel, a suitable habitat, the generation setting and sufficient area levels. Static tables for unprovided cartridges are not asserted here.</div>
<h2>Species habitat index</h2><label for="search">Search species, National number or habitat</label><input id="search" type="search" placeholder="Jigglypuff, 39, forest…"><p id="count"></p><div class="table"><table><thead><tr><th>National</th><th>Species</th><th>Generation</th><th>Habitat</th><th>Added level threshold</th><th>Unlock</th></tr></thead><tbody id="rows"></tbody></table></div><footer>Self-contained guide. No network requests. Exact cartridge encounters, gifts and trades are outside this habitat index.</footer></main>
<script>const data=@@DATA@@,ultra=new Set([793,794,795,796,797,798,799,803,804,805,806]);const search=document.getElementById('search');function draw(){const q=search.value.trim().toLowerCase();const rows=data.filter(r=>!q||r.name.toLowerCase().includes(q)||String(r.id)===q||r.habitat.includes(q));document.getElementById('count').textContent=rows.length+' species';document.getElementById('rows').innerHTML=rows.map(r=>'<tr><td>#'+String(r.id).padStart(4,'0')+'</td><td>'+r.name.replaceAll('_',' ')+'</td><td>'+r.gen+'</td><td>'+r.habitat+'</td><td>'+r.gate+'</td><td>'+((r.special||ultra.has(r.id))?'League clear':'Area progression')+'</td></tr>').join('')}search.addEventListener('input',draw);draw();</script></html>'''
(out/'All-Games-Encounter-Companion-v1.2.14.html').write_text(companion.replace('@@DATA@@',data),encoding='utf-8')
